# Generated by Django 5.0.6 on 2024-06-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepautoservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_apointments',
            old_name='start_time',
            new_name='datum',
        ),
        migrations.RenameField(
            model_name='service_apointments',
            old_name='levertijd',
            new_name='tijd',
        ),
        migrations.RemoveField(
            model_name='service_apointments',
            name='client',
        ),
        migrations.RemoveField(
            model_name='service_apointments',
            name='ordernr',
        ),
        migrations.RemoveField(
            model_name='service_apointments',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='service_apointments',
            name='sity',
        ),
        migrations.RemoveField(
            model_name='service_apointments',
            name='telefon',
        ),
        migrations.AddField(
            model_name='service_apointments',
            name='Omschrijving',
            field=models.CharField(max_length=500, null=True, verbose_name='Omschrijving'),
        ),
        migrations.AddField(
            model_name='service_apointments',
            name='functie',
            field=models.CharField(max_length=150, null=True, verbose_name='functie'),
        ),
        migrations.AddField(
            model_name='service_apointments',
            name='kenteken',
            field=models.CharField(max_length=47, null=True, verbose_name='Kenteken'),
        ),
    ]
